show_downloads: true

theme: jekyll-theme-minimal

lsi: false
safe: true
source: ../
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
